#!/bin/bash
# PreToolUse hook: Block direct edits to auto-generated marketplace.json
# Registered on Write|Edit tools
INPUT=$(head -c 65536)
if ! printf '%s' "$INPUT" | jq -e . >/dev/null 2>&1; then
  echo '{"decision": "approve"}'
  exit 0
fi

FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // ""')

# Normalize path separators for Windows
FILE=$(printf '%s' "$FILE" | tr '\\' '/')

if printf '%s' "$FILE" | grep -qiF '.claude-plugin/marketplace.json'; then
  jq -n '{"decision":"block","reason":"marketplace.json is auto-generated by CI. Do not edit directly. Modify plugins and run: node tools/generate-marketplace-json.js"}'
  exit 0
fi

echo '{"decision": "approve"}'
